# Generated by Django 2.2 on 2019-05-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_auto_20190530_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensdopedido',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
